package cs5621.project2.job2;

import java.io.IOException;

import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Mapper;

public class Job2Mapper extends Mapper<LongWritable, Text, Text, Text> {
	
	
	/**
	 * Mapper operation for the second job, where we calculate distances between intersections.
	 * 
	 * Output:
	 * 		Key: < WayID, Way Name, Node Index >
	 * 		Value: < lat, lon, node ID, node index, and intersection flag >
	 */
	@Override
	public void map(LongWritable key, Text value, Context context) throws IOException, InterruptedException {
		
		/*
		 * Split the key generated by the previous MapReduce job assuming the following format:
		 * <Key> '\t' <Val.1 Val.2 Val.3>
		 * 
		 * Key is split by tab characters and values are split by a single space.
		 */
		String part[] = value.toString().split("\t");
			
		
		context.write(new Text(part[0]),new Text(part[1]));
	}
	
}
